'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Database, Moon, Search, Settings, Sun, TerminalSquare } from 'lucide-react';
import { appNavigation, labNavigation, shellCopy } from '@/config/app-shell';

function NavItem({ href, label, active }: { href: string; label: string; active: boolean }) {
  return <Link href={href} className={`flex items-center rounded-lg px-3 py-2 text-sm transition ${active ? 'bg-[var(--accent-soft)] text-[var(--accent)]' : 'text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--foreground)]'}`}>{label}</Link>;
}

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><header className="sticky top-0 z-40 h-14 border-b border-[var(--border)] bg-[var(--background)]/95 backdrop-blur"><div className="flex h-full items-center gap-4 px-4 lg:px-6"><div className="flex min-w-0 items-center gap-3"><div className="flex size-8 items-center justify-center rounded-lg bg-[var(--accent)] text-white"><Database size={17}/></div><div className="hidden sm:block"><div className="text-sm font-semibold tracking-tight">{shellCopy.product}</div><div className="text-[10px] text-[var(--muted)]">{shellCopy.environment}</div></div></div><div className="ml-auto flex items-center gap-2"><button className="hidden md:flex items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-1.5 text-xs text-[var(--muted)]"><Search size={14}/> {shellCopy.search}<kbd className="rounded border border-[var(--border)] px-1 text-[9px]">⌘K</kbd></button><span className="hidden sm:flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-1.5 text-[10px]"><span className="size-1.5 rounded-full bg-emerald-500"/> {shellCopy.connected}</span><button aria-label={shellCopy.lightTheme} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-hover)]"><Sun size={16}/></button><button aria-label={shellCopy.settings} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-hover)]"><Settings size={16}/></button></div></div></header><div className="flex min-h-[calc(100vh-3.5rem)]"><aside className="hidden w-60 shrink-0 border-r border-[var(--border)] bg-[var(--surface)] p-3 lg:block"><div className="mb-5 px-3 pt-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--muted)]">Workspace</div><nav className="space-y-1">{appNavigation.map((item) => <NavItem key={item.id} {...item} active={pathname === item.href}/>)}</nav><div className="mb-3 mt-8 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--muted)]">Interactive labs</div><nav className="space-y-1">{labNavigation.map((item) => <NavItem key={item.id} {...item} active={pathname === item.href}/>)}</nav><div className="mt-8 rounded-xl border border-[var(--border)] bg-[var(--background)] p-3"><div className="flex items-center gap-2 text-xs font-medium"><TerminalSquare size={14} className="text-[var(--accent)]"/> PostgreSQL</div><div className="mt-2 text-[10px] leading-4 text-[var(--muted)]">Interactive database demonstrations and SQL experiments.</div></div></aside><main className="min-w-0 flex-1">{children}</main></div></div>;
}
