/**
 * Demo dataset shared by every lesson: a tiny multi-tenant task tracker.
 * Idempotent — rerunning drops and rebuilds the `lab` schema. Roles are cluster-wide,
 * so they are created only if missing and never dropped.
 *
 * Security features (RLS, policies, triggers) are intentionally NOT enabled here;
 * lessons turn them on step by step so learners see the before/after.
 */
export const SEED_SQL = `
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_member') THEN CREATE ROLE app_member NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin')  THEN CREATE ROLE app_admin  NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_anon')   THEN CREATE ROLE app_anon   NOLOGIN; END IF;
END $$;

DROP SCHEMA IF EXISTS lab CASCADE;
CREATE SCHEMA lab;
SET search_path = lab;

CREATE TABLE organizations (
  id    int PRIMARY KEY,
  name  text NOT NULL,
  plan  text NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro'))
);

CREATE TABLE members (
  id      int PRIMARY KEY,
  org_id  int NOT NULL REFERENCES organizations(id),
  name    text NOT NULL,
  email   text NOT NULL UNIQUE,
  role    text NOT NULL CHECK (role IN ('owner', 'member'))
);

CREATE TABLE projects (
  id      int PRIMARY KEY,
  org_id  int NOT NULL REFERENCES organizations(id),
  name    text NOT NULL,
  budget  numeric(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE tasks (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id       int NOT NULL REFERENCES organizations(id),
  project_id   int NOT NULL REFERENCES projects(id),
  title        text NOT NULL,
  status       text NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'doing', 'done')),
  assignee_id  int REFERENCES members(id),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  table_name  text NOT NULL,
  op          text NOT NULL,
  row_id      bigint,
  old_data    jsonb,
  new_data    jsonb,
  changed_by  text NOT NULL DEFAULT current_user,
  changed_at  timestamptz NOT NULL DEFAULT now()
);

-- "Who is calling?" — the app sets these per request, e.g. SELECT set_config('app.member_id', '1', false);
CREATE FUNCTION current_member_id() RETURNS int
  LANGUAGE sql STABLE
  AS $fn$ SELECT nullif(current_setting('app.member_id', true), '')::int $fn$;

CREATE FUNCTION current_org_id() RETURNS int
  LANGUAGE sql STABLE
  AS $fn$ SELECT nullif(current_setting('app.org_id', true), '')::int $fn$;

INSERT INTO organizations VALUES (1, 'Acme Rockets', 'pro'), (2, 'Globex Labs', 'free');

INSERT INTO members VALUES
  (1, 1, 'Alice', 'alice@acme.test', 'owner'),
  (2, 1, 'Bob',   'bob@acme.test',   'member'),
  (3, 2, 'Carol', 'carol@globex.test', 'owner'),
  (4, 2, 'Dan',   'dan@globex.test',   'member');

INSERT INTO projects VALUES
  (1, 1, 'Moon Rocket', 50000), (2, 1, 'Website', 4000), (3, 2, 'Mobile App', 12000);

INSERT INTO tasks (org_id, project_id, title, status, assignee_id) VALUES
  (1, 1, 'Design fuel tank',        'doing', 1),
  (1, 1, 'Order 3 tons of rocket fuel', 'todo', 2),
  (1, 2, 'Fix landing page typo',   'done',  2),
  (1, 2, 'Add pricing page',        'todo',  NULL),
  (2, 3, 'Login screen',            'doing', 4),
  (2, 3, 'Push notifications',      'todo',  3),
  (2, 3, 'Secret launch plan',      'todo',  3);

GRANT USAGE ON SCHEMA lab TO app_member, app_admin, app_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA lab TO app_member, app_admin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA lab TO app_member, app_admin;
GRANT SELECT ON organizations TO app_anon;
`;

/** Detects whether the demo schema exists. */
export const SEED_CHECK_SQL = `SELECT to_regclass('lab.tasks') IS NOT NULL AS seeded`;
