'use client';

import { ChevronDown, KeyRound, Link2, ShieldCheck, Zap } from 'lucide-react';
import { useState } from 'react';
import { schemaConfig } from '@/config/schema';

export function SchemaExplorer() {
  const [open, setOpen] = useState<string | null>(schemaConfig.tables[0]?.name ?? null);
  return <div className="glass rounded-2xl p-5"><div className="mb-4"><div className="text-sm font-semibold">Schema explorer</div><div className="mt-1 text-[11px] text-[var(--muted)]">{schemaConfig.database} · {schemaConfig.schema}</div></div><div className="space-y-2">{schemaConfig.tables.map((table) => { const expanded = open === table.name; return <div key={table.name} className="overflow-hidden rounded-xl border border-[var(--line)]"><button onClick={() => setOpen(expanded ? null : table.name)} className="flex w-full items-center gap-3 p-3 text-left hover:bg-white/[.025]"><ChevronDown size={14} className={`transition ${expanded ? 'rotate-0' : '-rotate-90'}`}/><span className="text-xs font-semibold">{table.name}</span><span className="ml-auto text-[10px] text-slate-500">{table.columns.length} columns</span></button>{expanded && <div className="border-t border-[var(--line)] p-3"><div className="space-y-1">{table.columns.map((column) => <div key={column.name} className="flex items-center gap-2 rounded-lg px-2 py-2 text-[11px] hover:bg-white/[.025]">{column.key === 'PK' ? <KeyRound size={12} className="text-amber-300"/> : column.key === 'FK' ? <Link2 size={12} className="text-cyan-300"/> : <span className="w-3"/>}<span className="font-mono text-slate-300">{column.name}</span><span className="ml-auto text-slate-500">{column.type}</span></div>)}</div>{table.policies.length > 0 && <div className="mt-3 rounded-lg border border-emerald-400/15 bg-emerald-400/[.03] p-3"><div className="flex items-center gap-2 text-[11px] font-medium text-emerald-300"><ShieldCheck size={13}/> {table.policies.length} RLS policy</div>{table.policies.map((policy) => <div key={policy.name} className="mt-2 font-mono text-[10px] text-slate-500">{policy.name} · USING {policy.using}</div>)}</div>}{table.triggers.length > 0 && <div className="mt-2 rounded-lg border border-orange-400/15 bg-orange-400/[.03] p-3"><div className="flex items-center gap-2 text-[11px] font-medium text-orange-300"><Zap size={13}/> {table.triggers.length} trigger</div>{table.triggers.map((trigger) => <div key={trigger.name} className="mt-2 font-mono text-[10px] text-slate-500">{trigger.name} · {trigger.event} → {trigger.function}</div>)}</div>}</div>}</div>})}</div></div>;
}
