'use client';

import { useMemo, useState } from 'react';
import { Check, Plus, Trash2 } from 'lucide-react';
import { triggerEvents, triggerLabCopy, triggerLevels, triggerTimings } from '@/config/triggers-lab';
import { buildCreateTriggerSql, type TriggerDraft } from '@/lib/trigger-sql';

const defaults: TriggerDraft = { schema: 'public', table: 'orders', name: 'orders_audit', functionSchema: 'public', functionName: 'audit_order_change', timing: 'AFTER', events: ['INSERT', 'UPDATE'], level: 'ROW' };

export function TriggerLab() {
  const [draft, setDraft] = useState<TriggerDraft>(defaults);
  const sql = useMemo(() => { try { return buildCreateTriggerSql(draft); } catch (error) { return error instanceof Error ? error.message : ''; } }, [draft]);
  const update = (patch: Partial<TriggerDraft>) => setDraft((current) => ({ ...current, ...patch }));
  const toggleEvent = (event: string) => setDraft((current) => ({ ...current, events: current.events.includes(event) ? current.events.filter((item) => item !== event) : [...current.events, event] }));
  return <div className="glass rounded-2xl p-5"><div className="mb-5 flex items-start justify-between"><div><div className="text-sm font-semibold">{triggerLabCopy.title}</div><div className="text-[10px] text-slate-500">Connect table events to a database function.</div></div><Plus size={17} className="text-cyan-300"/></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-slate-400">Schema<input value={draft.schema} onChange={(e) => update({ schema: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label><label className="text-[10px] text-slate-400">Table<input value={draft.table} onChange={(e) => update({ table: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label><label className="text-[10px] text-slate-400">Trigger name<input value={draft.name} onChange={(e) => update({ name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label><label className="text-[10px] text-slate-400">Trigger function<input value={draft.functionName} onChange={(e) => update({ functionName: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label><label className="text-[10px] text-slate-400">{triggerLabCopy.timing}<select value={draft.timing} onChange={(e) => update({ timing: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white">{triggerTimings.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-[10px] text-slate-400">{triggerLabCopy.level}<select value={draft.level} onChange={(e) => update({ level: e.target.value })} className="mt-1.5 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white">{triggerLevels.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="mt-5"><div className="mb-2 text-[10px] text-slate-400">{triggerLabCopy.event}</div><div className="flex flex-wrap gap-2">{triggerEvents.map((event) => <button key={event} onClick={() => toggleEvent(event)} className={`rounded-lg border px-3 py-2 text-[10px] transition ${draft.events.includes(event) ? 'border-cyan-300/40 bg-cyan-300/[.08] text-cyan-100' : 'border-[var(--line)] text-slate-500'}`}>{draft.events.includes(event) && <Check size={11} className="mr-1 inline"/>}{event}</button>)}</div></div><div className="mt-5 rounded-xl border border-[var(--line)] bg-black/20 p-4"><div className="mb-2 text-[10px] font-semibold text-slate-400">{triggerLabCopy.preview}</div><pre className="overflow-x-auto text-[10px] leading-5 text-cyan-100">{sql}</pre></div></div>;
}
