'use client';

import { useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { postgresTypes, tableBuilderCopy, tableBuilderDefaults } from '@/config/table-builder';
import { buildCreateTableSql, type TableColumnDraft } from '@/lib/table-sql';

export function TableBuilder() {
  const [schema, setSchema] = useState(tableBuilderDefaults.schema);
  const [table, setTable] = useState('');
  const [columns, setColumns] = useState<TableColumnDraft[]>([{ name: 'id', type: 'uuid', nullable: false, primaryKey: true }]);
  const sql = useMemo(() => { try { return buildCreateTableSql(schema, table || 'table_name', columns); } catch (error) { return error instanceof Error ? error.message : ''; } }, [schema, table, columns]);
  const update = (index: number, patch: Partial<TableColumnDraft>) => setColumns((current) => current.map((column, i) => i === index ? { ...column, ...patch } : column));
  return <div className="glass rounded-2xl p-5"><div className="mb-4"><div className="text-sm font-semibold">{tableBuilderCopy.title}</div><div className="text-[10px] text-slate-500">Design the table and inspect the generated PostgreSQL before execution.</div></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-slate-400">Schema<input value={schema} onChange={(e) => setSchema(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label><label className="text-[10px] text-slate-400">Table name<input value={table} onChange={(e) => setTable(e.target.value)} placeholder="orders" className="mt-1 w-full rounded-xl border border-[var(--line)] bg-black/20 px-3 py-2 text-xs text-white"/></label></div><div className="mt-4 space-y-2">{columns.map((column, index) => <div key={`${index}-${column.name}`} className="grid gap-2 rounded-xl border border-[var(--line)] p-3 sm:grid-cols-[1.3fr_1fr_auto_auto_auto]"><input value={column.name} onChange={(e) => update(index, { name: e.target.value })} placeholder="column" className="rounded-lg bg-black/20 px-2 py-2 text-xs text-white"/><select value={column.type} onChange={(e) => update(index, { type: e.target.value })} className="rounded-lg bg-black/20 px-2 py-2 text-xs text-white">{postgresTypes.map((type) => <option key={type}>{type}</option>)}</select><label className="flex items-center gap-1 text-[10px] text-slate-400"><input type="checkbox" checked={column.nullable} disabled={column.primaryKey} onChange={(e) => update(index, { nullable: e.target.checked })}/> Nullable</label><label className="flex items-center gap-1 text-[10px] text-slate-400"><input type="checkbox" checked={column.primaryKey} onChange={(e) => update(index, { primaryKey: e.target.checked, nullable: e.target.checked ? false : column.nullable })}/> PK</label><button onClick={() => setColumns((current) => current.filter((_, i) => i !== index))} disabled={columns.length === 1} className="text-slate-500 hover:text-red-300"><Trash2 size={14}/></button></div>)}</div><button onClick={() => setColumns((current) => [...current, { name: '', type: 'text', nullable: true, primaryKey: false }])} className="mt-3 text-[10px] text-cyan-300"><Plus size={12} className="mr-1 inline"/>{tableBuilderCopy.addColumn}</button><div className="mt-5 rounded-xl border border-[var(--line)] bg-black/20 p-4"><div className="mb-2 text-[10px] font-semibold text-slate-400">{tableBuilderCopy.preview}</div><pre className="overflow-x-auto text-[11px] leading-5 text-cyan-100">{sql}</pre></div></div>;
}
